from sentence_transformers import SentenceTransformer, util
from PIL import Image
import requests
import torch


animals_ru = [
"Орешниковая соня",
"Водяная полевка",
"Заяц",
"Обыкновенный ёж",
"Обыкновенная водяная землеройка",
"Водяная летучая мышь",
"Двухцветная кожистая",
"Лесная летучая мышь",
"Брандтова летучая мышь",
"Бурый ушастик",
"Рыжая вечерница",
"Горностай",
"Ласка",
"Хорек",
"Барсук",
"Каменная куница",
"Лесная куница",
"Гнездо"
]

animals_en = [
        "Hazel Dormouse",
        "Water Vole",
        "Hare",
        "Common Hedgehog",
        "Common Water Shrew",
        "Water Bat",
        "Two-colored Leatherback",
        "Forest Bat",
        "Brandt's Bat",
        "Brown Long-eared Bat",
        "Red Noctule",
        "Ermine",
        "Weasel",
        "Polecat",
        "Badger",
        "Stone Marten",
        "Pine Marten",
        "Nest"
]

# Список русских названий
plants_ru = [
    "Астрагал датский",
    "Астрагал песчаный",
    "Астрагал солодколистный",
    "Багульник болотный",
    "Баранец обыкновенный",
    "Белоус торчащий",
    "Берёза приземистая",
    "Болотный мирт",
    "Борец северный, или Борец высокий",
    "Бородник шароносный, или Молодило побегоносное",
    "Бузульник сибирский",
    "Вереск обыкновенный",
    "Вероника широколистная",
    "Ветреница дубравная",
    "Ветреница лютиковая",
    "Волчье лыко обыкновенное",
    "Воробейник лекарственный",
    "Гвоздика травянка",
    "Гвоздика Фишера",
    "Герань Роберта",
    "Гнездовка настоящая",
    "Голубика",
    "Горец змеиный, или Раковые шейки",
    "Горечавка крестовидная",
    "Горечавка лёгочная",
    "Горицвет кукушкин",
    "Горошек кашубский",
    "Гроздовник полулунный",
    "Гудайера ползучая",
    "Двулепестник альпийский",
    "Дрёма двудомная",
    "Дремлик болотный",
    "Дремлик широколистный",
    "Ежеголовник малый",
    "Земляника зелёная, или Земляника луговая",
    "Зиглингия лежачая",
    "Золототысячник обыкновенный",
    "Ирис жёлтый, или Ирис аировидный",
    "Истод горьковатый",
    "Истод обыкновенный",
    "Истод хохлатый",
    "Калужница болотная",
    "Клюква болотная",
    "Колокольчик болонский",
    "Колокольчик крапиволистный",
    "Колокольчик круглолистный",
    "Колокольчик олений, или Колокольчик жёстковолосистый",
    "Колокольчик персиколистный",
    "Колокольчик раскидистый",
    "Колокольчик широколистный",
    "Колючник обыкновенный",
    "Котовник венгерский",
    "Кошачья лапка двудомная",
    "Кувшинка белоснежная",
    "Купальница европейская",
    "Купена душистая, или Купена лекарственная",
    "Купена многоцветковая",
    "Ладьян трёхнадрезный",
    "Ландыш майский",
    "Линнея северная",
    "Лук круглый, или Лук Вальдштейна",
    "Лук огородный",
    "Лук угловатый",
    "Любка двулистная",
    "Любка зеленоцветковая",
    "Лютик волосистолистный",
    "Лютик языколистный, или Лютик длиннолистный",
    "Медуница неясная",
    "Многорядник Брауна",
    "Можжевельник обыкновенный",
    "Мытник болотный",
    "Мякотница однолистная",
    "Незабудка болотная",
    "Нивяник обыкновенный",
    "Нонея тёмно-бурая",
    "Овсик извилистый",
    "Овсяница валлисская, или Типчак",
    "Овсяница высокая",
    "Омфалодес ползучий, или Пупочник",
    "Осока пушистоплодная",
    "Осока топяная",
    "Пальчатокоренник балтийский",
    "Пальчатокоренник гебридский",
    "Пальчатокоренник кровавый",
    "Пальчатокоренник мясо-красный",
    "Пальчатокоренник пятнистый",
    "Пальчатокоренник Фукса",
    "Первоцвет весенний",
    "Печёночница благородная",
    "Плаун булавовидный",
    "Плаун годичный",
    "Подбел обыкновенный",
    "Подлесник европейский",
    "Подъельник обыкновенный",
    "Посконник коноплёвый",
    "Пупавка красильная",
    "Пушица влагалищная",
    "Пушица многоколосковая",
    "Росянка круглолистная",
    "Синеголовник плосколистный",
    "Синюха голубая",
    "Смолка обыкновенная",
    "Страусник обыкновенный",
    "Таволга обыкновенная",
    "Тайник яйцевидный",
    "Телиптерис болотный",
    "Тимофеевка степная",
    "Тимьян блошиный, или Чабрец блошиный",
    "Тимьян Лёви, или Чабрец Лёви",
    "Тимьян Маршалла, или Чабрец Маршалла",
    "Фиалка трёхцветная",
    "Хвощ ветвистый",
    "Хвощ пёстрый",
    "Хохлатка Маршалла",
    "Хохлатка плотная",
    "Хохлатка полая",
    "Хохлатка промежуточная",
    "Чина весенняя",
    "Чина чёрная",
    "Шейхцерия болотная",
    "Щитовник гребенчатый",
    "Язвенник обыкновенный"
]

# Список английских названий
plants_en = [
    "Danish Astragalus",
    "Sand Astragalus",
    "Glycyphyllus Astragalus",
    "Marsh Ledum",
    "Common Huperzia",
    "Nardus Grass",
    "Dwarf Birch",
    "Bog Myrtle",
    "Northern Monkshood, or Tall Monkshood",
    "Woolly Stonecrop, or Creeping Houseleek",
    "Siberian Ligularia",
    "Common Heather",
    "Broadleaf Veronica",
    "Wood Anemone",
    "Buttercup Anemone",
    "Common Daphne",
    "Medicinal Lithospermum",
    "Meadow Pink",
    "Fisher's Pink",
    "Robert's Geranium",
    "True Bird's Nest",
    "Blueberry",
    "Snake Dock, or Cancer Neck",
    "Cross Gentian",
    "Lung Gentian",
    "Cuckoo Flower",
    "Kashubian Pea",
    "Halfmoon Grapevine",
    "Creeping Goodyera",
    "Alpine Circaea",
    "Two-Seeded Sleepwort",
    "Marsh Epipactis",
    "Broadleaf Epipactis",
    "Lesser Bur-reed",
    "Green Strawberry, or Meadow Strawberry",
    "Decumbent Sieglingia",
    "Common Centaury",
    "Bitter Polygala",
    "Common Polygala",
    "Fringed Polygala",
    "Marsh Caltha",
    "Bog Cranberry",
    "Bologna Bellflower",
    "Nettle-leaved Bellflower",
    "Round-leaved Bellflower",
    "Reindeer Bellflower, or Stiff-haired Bellflower",
    "Peach-leaved Bellflower",
    "Spreading Bellflower",
    "Broadleaf Bellflower",
    "Common Carline Thistle",
    "Hungarian Catmint",
    "Two-Leafed Antennaria",
    "White Water Lily",
    "European Trollius",
    "Fragrant Solomon's Seal, or Medicinal Solomon's Seal",
    "Multiflora Solomon's Seal",
    "Three-lobed Corallorhiza",
    "May Lily",
    "Northern Linnaea",
    "Round-leaved Onion, or Waldstein's Onion",
    "Garden Onion",
    "Angled Onion",
    "Two-leaved Liparis",
    "Green-flowered Liparis",
    "Hairy Buttercup",
    "Ribwort Plantain, or Long-leafed Buttercup",
    "Unclear Pulmonaria",
    "Braun's Polystichum",
    "Common Juniper",
    "Marsh Pedicularis",
    "One-leafed Malaxis",
    "Marsh Forget-me-not",
    "Common Daisy",
    "Dark-brown Nonea",
    "Wavy Avenella",
    "Wallis Fescue, or Typchak",
    "Tall Fescue",
    "Creeping Omphalodes, or Pupil Plant",
    "Hairy Sedge",
    "Peat Sedge",
    "Baltic Dactylorhiza",
    "Hebrides Dactylorhiza",
    "Bloody Dactylorhiza",
    "Flesh-colored Dactylorhiza",
    "Spotted Dactylorhiza",
    "Fuchs's Dactylorhiza",
    "Spring Primrose",
    "Noble Hepatica",
    "Clubmoss",
    "Annual Clubmoss",
    "Common Andromeda",
    "European Sanicula",
    "Common Monotropa",
    "Hemp Eupatorium",
    "Dyer's Chamomile",
    "Vaginal Cotton Grass",
    "Many-flowered Cotton Grass",
    "Round-leaved Sundew",
    "Flat-leaved Eryngium",
    "Blue Polemonium",
    "Common Silene",
    "Common Matteuccia",
    "Common Filipendula",
    "Oval Listera",
    "Marsh Thelypteris",
    "Steppe Timothy",
    "Flea Thyme, or Flea Thymus",
    "Leovi Thyme, or Leovi Thymus",
    "Marshall's Thyme, or Marshall's Thymus",
    "Tri-color Violet",
    "Branching Horsetail",
    "Variegated Horsetail",
    "Marshall's Corydalis",
    "Dense Corydalis",
    "Hollow Corydalis",
    "Intermediate Corydalis",
    "Spring Lathyrus",
    "Black Lathyrus",
    "Marsh Scheuchzeria",
    "Crest Dryopteris",
    "Common Yarrow"
]

total_en = plants_en+animals_en
total_ru = plants_ru+animals_ru

class CLIPImageClassifier:
    def __init__(self):
        # Load the image and text models
        self.model = SentenceTransformer('clip-ViT-L-14')
        self.texts= [f"This is a {s.lower()}." for s in 
        total_en]

        self.text_embeddings = self.model.encode(self.texts, convert_to_tensor=True)
    
    def classify_image(self, image: Image.Image):
        # Encode the image
        img_embedding = self.model.encode(image, convert_to_tensor=True)
        
        # Compute cosine similarities
        cos_sim = util.cos_sim(self.text_embeddings, img_embedding)
        
        # Find the best matching text
        max_score, max_idx = torch.max(cos_sim, dim=0)
        return {
            "class": total_ru[max_idx],
            "prob": max_score.item()
        }
